name: Jottre
options:
  bundleIdPrefix: com.antonlorani
  deploymentTarget:
    iOS: "15.0"
  knownRegions:
    - en
    - de

targets:
  Jottre:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - Sources
      - path: Resources/Assets.xcassets
      - path: Resources/Localizable.xcstrings
      - path: Resources/Info.plist
        buildPhase: none
    info:
      path: Resources/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: "Default Configuration"
                UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.antonlorani.jottre
        PRODUCT_NAME: Jottre
        SWIFT_VERSION: "5.10"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTS_MACCATALYST: YES
        DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: NO
        BUNDLE_IDENTIFIER_MACCATALYST: com.antonlorani.jottre
        SWIFT_EMIT_LOC_STRINGS: YES
    packages: []
